[package]
name = "cordoba"
version = "0.1.0"
authors = ["Jonathan Bastien-Filiatrault <joe@x2a.org>"]

[profile.release]
panic = "abort"

[dependencies]
byteorder = "1"
memmap = { version="0.6.2", optional=true }

[features]
build-binary = ["memmap"]

[[bin]]
name = "cdbread"
required-features = ["build-binary"]

[[bin]]
name = "cdbwrite"
required-features = ["build-binary"]
