[package]
name = "cordoba"
version = "0.1.0"
authors = ["Jonathan Bastien-Filiatrault <joe@x2a.org>"]

[profile.release]
panic = "abort"

[dependencies]
byteorder = "1"
clap = { version="2.31", optional=true }
memmap = { version="0.6.2", optional=true }

[features]
default = ["build-binary"]
build-binary = ["clap", "memmap"]

[[bin]]
name = "cdb"
required-features = ["build-binary"]

[[bin]]
name = "cdbwrite"
required-features = ["build-binary"]
